name: "inorbitrocketseatfork"

services:
  db:
    image: "bitnami/postgresql:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=InOrbitApi
      - POSTGRES_PASSWORD=InOrbitApi123
      - POSTGRES_DB=InOrbitApiDatabase
  admin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - 8081:80

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
    driver: local